ARG BASE_IMG=pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel
FROM ${BASE_IMG}
MAINTAINER lsq<shangqinglyu@outlook.com>
WORKDIR /root/

# Copy scripts from file
COPY ./container/scripts/* /root/scripts/

# Prepare for basic environment
RUN echo "export LANG=C.UTF-8" >>/etc/profile \
&& apt-get update \
&& apt-get install -y dialog apt-utils \
&& DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata \
&& apt-get install vim openssh-server iputils-ping wget curl git htop tree gcc zip unzip ffmpeg libsm6 libxext6 libc6 -y \
# Allow remote login
&& sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config \
# Prepare for MiniConda
&& chmod 777 /root/scripts/miniconda-install.sh \
&& bash /root/scripts/miniconda-install.sh \
&& . /root/miniconda3/bin/activate \
&& conda update -n base -c defaults conda \
# Prepare for boot-up init script
&& chmod 777 /root/scripts/startup.sh \
# Modify welcome message
&& cp /root/scripts/welcome-message /etc/update-motd.d/10-help-text \
&& rm -rf /etc/update-motd.d/60-unminimize

# Make sure the environment is the same when logged in as ssh
RUN echo "export PATH=${PATH}" >> /root/.bashrc

# Prepare for Conda environment: python38
RUN chmod 777 /root/scripts/conda-torch-gpu-setup-python38.sh \
&& bash /root/scripts/conda-torch-gpu-setup-python38.sh

# Prepare OpenSlide for python38
RUN chmod 777 /root/scripts/conda-openslide-setup.sh \
&& bash /root/scripts/conda-openslide-setup.sh --conda_env python38

# Make sure the environment is the same when logged in as ssh
RUN echo "export PATH=${PATH}" >> /root/.bashrc

ENTRYPOINT /root/scripts/startup.sh
